### ISSUE TITLE
Change the dummy content beside this image.

### ISSUE THREAD

**Issue by Aini-Bashir** [Remy-Reveltek/silkcorp#2]
![Screenshot 2023-02-22 195954](https://user-images.githubusercontent.com/117284277/220661628-e9b30603-b10d-4892-bf0b-e387b185a96e.png)

Hello everyone. 
We are thrilled to announce that our SILK website is nearing completion, and we are currently in the process of updating its images and content to align with our core values and mission. SILK represents Strength, Intelligence, Love, and Kindness, and embodies our commitment to mental, physical, and spiritual wellness, perception and management, caring and hospitality, and community sharing and philanthropy.
SILK is an energy that fosters collective growth and enables individuals to achieve their best potential. We encourage you to consider our values and mission while creating content for our website, which reflects our vibrant culture and community. 
Follow these Instructions:
- Always consider perfect character count.
- Always use uppercase letters when you are starting your Paragraph or even a single word.
- Write a quote, feedback, or anything suitable for our website. Your choice of content must reflect SILK's actions, core values, and current mission.
- Always consider perfect character count.
- Always use uppercase letters when you are starting your Paragraph or even a single word.
- Write a quote, feedback, or anything suitable for our website. Your choice of content must reflect SILK's actions, core values, and current mission.

Thank you for your support in advancing our mission to empower individuals and communities through Strength, Intelligence, Love, and Kindness.

**Comment by Aini-Bashir** [comment]
@Remy-Reveltek Can you please put labels on the issues? I don't have access to this.

**Comment by Remy-Reveltek** [comment]
Ok

**Comment by Remy-Reveltek** [comment]
I have worked on it and Submitted PR
