### ISSUE TITLE
Update the text under S.I.L.K (our values)

### ISSUE THREAD

**Issue by Aini-Bashir** [Remy-Reveltek/silkcorp#24]
![image](https://user-images.githubusercontent.com/117284277/228602750-399eef8c-7c09-47a0-b85a-9c0e862d9a75.png)
![image](https://user-images.githubusercontent.com/117284277/228602904-07ff430a-1c4b-45ae-8361-15b14cf67707.png)

The text behind these images is not representing our areas so, update the textual content for these areas that represents the value of "Integrity" and "Knowledge."

Consider the word count while updating the text.

Guide source: [SILK Yoga](https://silkyoga.org/)

**Comment by Aini-Bashir** [comment]
I have created this issue and working on it.

**Comment by Aini-Bashir** [comment]
@Remy-Reveltek, I have updated the text for both the "integrity" and "knowledge" areas.

**Comment by Remy-Reveltek** [comment]
@Aini-Bashir, add more text to integrity
![image](https://user-images.githubusercontent.com/117187551/228623436-79a5074b-7ec7-4d81-aadc-e8241a3ca276.png)

**Comment by Aini-Bashir** [comment]
Alright.

**Comment by Remy-Reveltek** [comment]
Everything is looking good except for this, fix it, and then I will push all the changes inside main Repo

**Comment by Aini-Bashir** [comment]
Okay. Understood.

**Comment by Remy-Reveltek** [comment]
@Aini-Bashir, please use the desktop version and also the live server. It will be good to see your own changes before committing.

**Comment by Aini-Bashir** [comment]
*updated the text
